/**
 * Gecureerde icon-set (lucide-react) — één plek zodat stijl/keuze consistent
 * blijft en eenvoudig te vervangen is. Gebruik: `import { Dumbbell } from "@/components/ui/icons"`.
 * Standaard stroke 1.9 (sluit aan op TopNav/MemberNav). Override met className/size.
 */
export {
  Dumbbell,
  Activity,
  Flame,
  Users,
  UserPlus,
  Calendar,
  CalendarDays,
  CalendarClock,
  ClipboardList,
  FileText,
  Send,
  LayoutDashboard,
  LineChart,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Settings,
  ScrollText,
  QrCode,
  Dumbbell as Weight,
  Zap,
  Heart,
  Timer,
  Trophy,
  Target,
  Plus,
  Minus,
  Pencil,
  Trash2,
  Search,
  Filter,
  Download,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  Play,
  Pause,
  RotateCcw,
  SkipForward,
  Volume2,
  VolumeX,
  Vibrate,
  LogOut,
  Sun,
  Moon,
  Bell,
  MapPin,
  Clock,
  Phone,
  Mail,
  Globe,
  Building2,
  Navigation,
  Sparkles,
  Info,
  GripVertical,
  Eye,
  EyeOff,
  ArrowUpRight,
  Maximize,
  Minimize,
} from "lucide-react";

export type { LucideIcon } from "lucide-react";
